version: '3.8'

services:
  node:
    image: node:18-alpine
    user: node
    working_dir: /home/node/bull-board-docker
    command: tail -f /dev/null
    ports:
      - 3000:3000
    volumes:
      - ./:/home/node/bull-board-docker

  redis:
    image: redis:7-alpine
